version: '3.4'

services:
  postgres:
    image: postgres:12.4-alpine
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - docker.env
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume: